name: "Submit to Web Store"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.11.0
          run_install: true
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 16.x
          cache: "pnpm"
      - name: Create .env file
        run: |
          touch .env
          echo PLASMO_PUBLIC_SOCKET_ENDPOINT=${{ secrets.PLASMO_PUBLIC_SOCKET_ENDPOINT }} >> .env
      - name: Build and zip chromium extension artifact
        run: pnpm build -- --zip
      - name: Chrome/Edge Platform Publish
        uses: PlasmoHQ/bpp@v2
        with:
          keys: ${{ secrets.SUBMIT_CHROMIUM }}
          artifact: build/chrome-mv3-prod.zip
      - name: Build and zip firefox extension artifact
        run: pnpm build -- --zip --target=firefox-mv2
      - name: Chrome/Edge Platform Publish
        uses: PlasmoHQ/bpp@v2
        with:
          keys: ${{ secrets.SUBMIT_FIREFOX }}
          artifact: build/chrome-mv3-prod.zip
